export const MESSAGE_ID_STORAGE_UPDATED = 'STORAGE_UPDATED'
export const MESSAGE_ID_STORAGE_UPDATE_REQUEST = 'STORAGE_UPDATE_REQUEST'
export const MESSAGE_ID_BLOCKED_TAB_ACTION = 'BLOCKED_TAB_ACTION'
